config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :portafolios

  resources :certificacions

  resources :informacions

  resources :acontecimientos

  resources :servicios

  resources :contactos

  devise_scope :usuario do
    get "/login" => "devise/sessions#new"
  end

  root 'principal#index'

  get "/admin" => "admin#index"

end

app/models/certificacion.rb
class Certificacion < ActiveRecord::Base
	has_attached_file :foto
  	validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
end

app/controllers/certificacions_controller.rb
class CertificacionsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_certificacion, only: [:show, :edit, :update, :destroy]

  # GET /certificacions
  # GET /certificacions.json
  def index
    @certificacions = Certificacion.all
  end

  # GET /certificacions/1
  # GET /certificacions/1.json
  def show
  end

  # GET /certificacions/new
  def new
    @certificacion = Certificacion.new
  end

  # GET /certificacions/1/edit
  def edit
  end

  # POST /certificacions
  # POST /certificacions.json
  def create
    @certificacion = Certificacion.new(certificacion_params)

    respond_to do |format|
      if @certificacion.save
        format.html { redirect_to @certificacion, notice: 'Certificacion was successfully created.' }
        format.json { render :show, status: :created, location: @certificacion }
      else
        format.html { render :new }
        format.json { render json: @certificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificacions/1
  # PATCH/PUT /certificacions/1.json
  def update
    respond_to do |format|
      if @certificacion.update(certificacion_params)
        format.html { redirect_to @certificacion, notice: 'Certificacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificacion }
      else
        format.html { render :edit }
        format.json { render json: @certificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificacions/1
  # DELETE /certificacions/1.json
  def destroy
    @certificacion.destroy
    respond_to do |format|
      format.html { redirect_to certificacions_url, notice: 'Certificacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificacion
      @certificacion = Certificacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificacion_params
      params.require(:certificacion).permit(:titulo_certificacion, :descripcion_certificacion, :foto)
    end
end

app/helpers/certificacions_helper.rb
module CertificacionsHelper
end

app/views/certificacions/_form.html.erb
<%= bootstrap_form_for(@certificacion) do |f| %>
  <% if @certificacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificacion.errors.count, "error") %> prohibited this certificacion from being saved:</h2>

      <ul>
      <% @certificacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :titulo_certificacion %>
    <%= f.text_area :descripcion_certificacion %>
    <%= f.file_field :foto %>
    <% if current_uri = request.env['PATH_INFO'].to_s == "/certificacions/"+@certificacion.id.to_s+"/edit" %>
      <%= f.submit "Editar certificacion" %>
    <% else %>
      <%= f.submit "Crear certificacion" %>
    <% end %>
<% end %>

app/views/certificacions/edit.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Editar certificacion</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Ver certificacion', @acontecimiento, :class=>"btn btn-success" %> 
<%= link_to 'Volver a certificaciones', certificacions_path, :class=>"btn btn-primary" %>
</div>
</div>

app/views/certificacions/index.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h2 style="text-align:center;">Listado de certificaciones</h2>
<div class="table-responsive">

<table class="table table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Titulo certificacion</th>
      <th>Descripcion certificacion</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificacions.each do |certificacion| %>
      <tr>
        <td><%= certificacion.titulo_certificacion %></td>
        <td><%= certificacion.descripcion_certificacion %></td>
        <td><img src="<%= certificacion.foto.url %>" width="100px;"></td>
        <td><%= link_to 'Ver', certificacion, :class => 'btn btn-success' %></td>
        <td><%= link_to 'Editar', edit_certificacion_path(certificacion), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Borrar', certificacion, method: :delete, data: { confirm: 'Esta seguro que desea borrar este certificado?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva certificacion', new_certificacion_path, :class=>"btn btn-primary" %>
<%= link_to 'Atras', :back, :class=>"btn btn-primary" %>
<%= link_to 'Volver a pagina de administracion', '/admin', :class=>"btn btn-success" %>
</div>
</div>
</div>

app/views/certificacions/new.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Nueva certificacion</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Volver a certificaciones', certificacions_path, :class=>"btn btn-success" %>
</div>
</div>

app/views/certificacions/show.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo certificacion:</strong>
  <%= @certificacion.titulo_certificacion %>
</p>

<p>
  <strong>Descripcion certificacion:</strong>
  <%= @certificacion.descripcion_certificacion %>
</p>
<p>
	<strong>Imagen:</strong><br>
	<img src="<%= @certificacion.foto.url %>" width="250px;">
</p>

<br>
<br>
<%= link_to 'Editar', edit_certificacion_path(@certificacion), :class=>"btn btn-warning" %> 
<%= link_to 'Atras', :back, :class=>"btn btn-success" %>
</div>
</div>