config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :portafolios

  resources :certificacions

  resources :informacions

  resources :acontecimientos

  resources :servicios

  resources :contactos

  devise_scope :usuario do
    get "/login" => "devise/sessions#new"
  end

  root 'principal#index'

  get "/admin" => "admin#index"

end

app/models/portafolio.rb
class Portafolio < ActiveRecord::Base
	has_attached_file :foto
  	validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
end

app/controllers/portafolios_controller.rb
class PortafoliosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_portafolio, only: [:show, :edit, :update, :destroy]

  # GET /portafolios
  # GET /portafolios.json
  def index
    @portafolios = Portafolio.all
  end

  # GET /portafolios/1
  # GET /portafolios/1.json
  def show
  end

  # GET /portafolios/new
  def new
    @portafolio = Portafolio.new
  end

  # GET /portafolios/1/edit
  def edit
  end

  # POST /portafolios
  # POST /portafolios.json
  def create
    @portafolio = Portafolio.new(portafolio_params)

    respond_to do |format|
      if @portafolio.save
        format.html { redirect_to @portafolio, notice: 'Portafolio was successfully created.' }
        format.json { render :show, status: :created, location: @portafolio }
      else
        format.html { render :new }
        format.json { render json: @portafolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portafolios/1
  # PATCH/PUT /portafolios/1.json
  def update
    respond_to do |format|
      if @portafolio.update(portafolio_params)
        format.html { redirect_to @portafolio, notice: 'Portafolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portafolio }
      else
        format.html { render :edit }
        format.json { render json: @portafolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portafolios/1
  # DELETE /portafolios/1.json
  def destroy
    @portafolio.destroy
    respond_to do |format|
      format.html { redirect_to portafolios_url, notice: 'Portafolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portafolio
      @portafolio = Portafolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portafolio_params
      params.require(:portafolio).permit(:titulo_portafolio, :descripcion_portafolio, :foto)
    end
end

app/helpers/portafolios_helper.rb
module PortafoliosHelper
end

app/views/portafolios/_form.html.erb
<%= bootstrap_form_for(@portafolio) do |f| %>
  <% if @portafolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portafolio.errors.count, "error") %> prohibited this portafolio from being saved:</h2>

      <ul>
      <% @portafolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :titulo_portafolio %>
    <%= f.text_area :descripcion_portafolio %>
    <%= f.file_field :foto %>
    <% if current_uri = request.env['PATH_INFO'].to_s == "/portafolios/"+@portafolio.id.to_s+"/edit" %>
      <%= f.submit "Editar imagen" %>
    <% else %>
      <%= f.submit "Crear imagen" %>
    <% end %>
<% end %>

app/views/portafolios/edit.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Editar imagen</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Ver imagen', @portafolio, :class=>"btn btn-success" %> 
<%= link_to 'Volver a imagenes', portafolios_path, :class=>"btn btn-primary" %>
</div>
</div>

app/views/portafolios/index.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h2 style="text-align:center;">Listado de Imagenes</h2>
<div class="table-responsive">

<table class="table table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Titulo portafolio</th>
      <th>Descripcion portafolio</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portafolios.each do |portafolio| %>
      <tr>
        <td><%= portafolio.titulo_portafolio %></td>
        <td><%= portafolio.descripcion_portafolio %></td>
        <td><img src="<%= portafolio.foto.url %>" height="200px;"></td>
        <td><%= link_to 'Ver', portafolio, :class=>"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_portafolio_path(portafolio), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Borrar', portafolio, method: :delete, data: { confirm: 'Esta seguro que desea borrar esta foto?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva imagen', new_portafolio_path, :class => "btn btn-primary" %>
<%= link_to 'Atras', :back, :class => "btn btn-primary" %>
<%= link_to 'Volver a pagina de administracion', '/admin', :class=>"btn btn-success" %>
</div>
</div>
</div>

app/views/portafolios/new.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Nueva imagen</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Volver a imagenes', portafolios_path, :class=>"btn btn-success" %>
</div>
</div>

app/views/portafolios/show.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo de la imagen:</strong>
  <%= @portafolio.titulo_portafolio %>
</p>

<p>
  <strong>Descripcion de la imagen:</strong>
  <%= @portafolio.descripcion_portafolio %>
</p>

<p>
	<strong>Imagen:</strong><br>
	<img src="<%= @portafolio.foto.url %>" width="250px;">
</p>

<%= link_to 'Editar', edit_portafolio_path(@portafolio), :class=>"btn btn-warning" %> 
<%= link_to 'Atras', :back, :class=>"btn btn-success" %>
</div>
</div>