config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :portafolios

  resources :certificacions

  resources :informacions

  resources :acontecimientos

  resources :servicios

  resources :contactos

  devise_scope :usuario do
    get "/login" => "devise/sessions#new"
  end

  root 'principal#index'

  get "/admin" => "admin#index"

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
	has_attached_file :foto
  	validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
	validates :nombre_servicio, :descripcion_servicio, presence: true
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:nombre_servicio, :descripcion_servicio,:foto)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= bootstrap_form_for(@servicio) do |f| %>
  <% if @servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% @servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :nombre_servicio, :maxlength => 50, :placeholder => "Ingrese el nombre del servicio" %>
    <%= f.text_area :descripcion_servicio, :size => "48x5",:maxlength => 50, :placeholder => "Ingrese la descripcion del servicio" %>
    <%= f.file_field :foto %>
    <% if current_uri = request.env['PATH_INFO'].to_s == "/servicios/"+@servicio.id.to_s+"/edit" %>
      <%= f.submit "Editar servicio" %>
    <% else %>
      <%= f.submit "Crear servicio" %>
    <% end %>
<% end %>

app/views/servicios/edit.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Editar servicio</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Volver a servicios', servicios_path, :class=>"btn btn-primary" %>
</div>
</div>

app/views/servicios/index.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h2 style="text-align:center;">Listado de Servicios</h2>
<div class="table-responsive">

<table class="table table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Nombre servicio</th>
      <th>Descripcion servicio</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.nombre_servicio %></td>
        <td><%= servicio.descripcion_servicio %></td>
        <td><img src="<%= servicio.foto.url %>" width="150px;"></td>
        <td><%= link_to 'Editar', edit_servicio_path(servicio), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Borrar', servicio, method: :delete, data: { confirm: 'Esta seguro que desea eliminar este servicio?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicio', new_servicio_path, :class=>"btn btn-primary" %>
<%= link_to 'Atras', :back, :class=>"btn btn-primary" %>
<%= link_to 'Volver a pagina de administracion', '/admin', :class=>"btn btn-success" %>
</div>
</div>
</div>

app/views/servicios/new.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Nuevo servicio</h1>

<%= render 'form' %>
<br>
<br>
<%= link_to 'Volver a servicios', servicios_path, :class=>"btn btn-success" %>
</div>
</div>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre servicio:</strong>
  <%= @servicio.nombre_servicio %>
</p>

<p>
  <strong>Descripcion servicio:</strong>
  <%= @servicio.descripcion_servicio %>
</p>

<%= link_to 'Edit', edit_servicio_path(@servicio) %> |
<%= link_to 'Back', servicios_path %>