config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :portafolios

  resources :certificacions

  resources :informacions

  resources :acontecimientos

  resources :servicios

  resources :contactos

  devise_scope :usuario do
    get "/login" => "devise/sessions#new"
  end

  root 'principal#index'

  get "/admin" => "admin#index"

end

app/models/acontecimiento.rb
class Acontecimiento < ActiveRecord::Base
	has_attached_file :foto
  	validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
	validates :periodo_acontecimiento, :titulo_acontecimiento, :descripcion_acontecimiento, presence: true
end

app/controllers/acontecimientos_controller.rb
class AcontecimientosController < ApplicationController
  before_action :authenticate_usuario!

  before_action :set_acontecimiento, only: [:show, :edit, :update, :destroy]

  # GET /acontecimientos
  # GET /acontecimientos.json
  def index
    @acontecimientos = Acontecimiento.all
  end

  # GET /acontecimientos/1
  # GET /acontecimientos/1.json
  def show
  end

  # GET /acontecimientos/new
  def new
    @acontecimiento = Acontecimiento.new
  end

  # GET /acontecimientos/1/edit
  def edit
  end

  # POST /acontecimientos
  # POST /acontecimientos.json
  def create
    @acontecimiento = Acontecimiento.new(acontecimiento_params)

    respond_to do |format|
      if @acontecimiento.save
        format.html { redirect_to @acontecimiento, notice: 'Acontecimiento was successfully created.' }
        format.json { render :show, status: :created, location: @acontecimiento }
      else
        format.html { render :new }
        format.json { render json: @acontecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acontecimientos/1
  # PATCH/PUT /acontecimientos/1.json
  def update
    respond_to do |format|
      if @acontecimiento.update(acontecimiento_params)
        format.html { redirect_to @acontecimiento, notice: 'Acontecimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @acontecimiento }
      else
        format.html { render :edit }
        format.json { render json: @acontecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acontecimientos/1
  # DELETE /acontecimientos/1.json
  def destroy
    @acontecimiento.destroy
    respond_to do |format|
      format.html { redirect_to acontecimientos_url, notice: 'Acontecimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acontecimiento
      @acontecimiento = Acontecimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acontecimiento_params
      params.require(:acontecimiento).permit(:periodo_acontecimiento, :titulo_acontecimiento, :descripcion_acontecimiento, :foto)
    end
end

app/helpers/acontecimientos_helper.rb
module AcontecimientosHelper
end

app/views/acontecimientos/_form.html.erb
<%= bootstrap_form_for(@acontecimiento) do |f| %>
  <% if @acontecimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acontecimiento.errors.count, "error") %> prohibited this acontecimiento from being saved:</h2>

      <ul>
      <% @acontecimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :periodo_acontecimiento %>
    <%= f.text_field :titulo_acontecimiento %>
    <%= f.text_area :descripcion_acontecimiento %>
    <%= f.file_field :foto %>
    <% if current_uri = request.env['PATH_INFO'].to_s == "/acontecimientos/"+@acontecimiento.id.to_s+"/edit" %>
      <%= f.submit "Editar acontecimiento" %>
    <% else %>
      <%= f.submit "Crear acontecimiento" %>
    <% end %>
<% end %>

app/views/acontecimientos/edit.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Editar acontecimiento</h1>

<%= render 'form' %>

<br>
<br>
<%= link_to 'Ver acontecimiento', @acontecimiento, :class=>"btn btn-success" %> 
<%= link_to 'Volver a acontecimientos', acontecimientos_path, :class=>"btn btn-primary" %>
</div>
</div>

app/views/acontecimientos/index.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h2 style="text-align:center;">Listado de Acontecimientos</h2>
<div class="table-responsive">

<table class="table table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Periodo acontecimiento</th>
      <th>Titulo acontecimiento</th>
      <th>Descripcion acontecimiento</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acontecimientos.each do |acontecimiento| %>
      <tr>
        <td><%= acontecimiento.periodo_acontecimiento %></td>
        <td><%= acontecimiento.titulo_acontecimiento %></td>
        <td><%= acontecimiento.descripcion_acontecimiento %></td>
        <td><img src="<%= acontecimiento.foto.url %>" width="100px;"></td>
        <td><%= link_to 'Ver', acontecimiento, :class => 'btn btn-success' %></td>
        <td><%= link_to 'Editar', edit_acontecimiento_path(acontecimiento),:class => 'btn btn-warning' %></td>
        <td><%= link_to 'Borrar', acontecimiento, method: :delete, data: { confirm: 'Esta seguro que desea borrar este acontecimiento?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'Nuevo Acontecimiento', new_acontecimiento_path, :class=>"btn btn-primary" %>
<%= link_to 'Atras', :back, :class=>"btn btn-primary" %>
<%= link_to 'Volver a pagina de administracion', '/admin', :class=>"btn btn-success" %>
</div>
</div>

app/views/acontecimientos/new.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<h1>Nuevo acontecimiento</h1>

<%= render 'form' %>
<br>
<br>
<%= link_to 'Volver a acontecimientos', acontecimientos_path, :class=>"btn btn-success" %>
</div>
</div>

app/views/acontecimientos/show.html.erb
<div class="container" style="margin-top:60px;">
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo acontecimiento:</strong>
  <%= @acontecimiento.titulo_acontecimiento %>
</p>

<p>
  <strong>Periodo acontecimiento:</strong>
  <%= @acontecimiento.periodo_acontecimiento %>
</p>

<p>
  <strong>Descripcion acontecimiento:</strong>
  <%= @acontecimiento.descripcion_acontecimiento %>
</p>

<p>
	<strong>Imagen:</strong><br>
	<img src="<%= @acontecimiento.foto.url %>" width="250px;"> 
</p>

<br>
<br>
<%= link_to 'Editar', edit_acontecimiento_path(@acontecimiento), :class=>"btn btn-warning" %> 
<%= link_to 'Atras', :back, :class=>"btn btn-success" %>
</div>
</div>